server:
  port: 9001

spring:
  datasource:
    url: jdbc:sqlserver://111.11.11.11\SEGNLS:11111:databaseName=nombre
    username: username
    password: pass
    driverClassName: com.microsof.sqlserver.jdbc.sqlServerDriver
  jpa:
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect-SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
