server:
  port: 9001

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=SchoolDb
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
      format-sql: true
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
