server:
  port: 9001

spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-D7VNBPC\\SQLEXPRESS;databaseName=SchoolDb
    username: sa
    password: 12345
    driverClassName: com.microsof.sqlserver.jdbc.sqlServerDriver
  jpa:
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect-SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
