server:
  port: 8081

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          default-label: main
          uri: https://github.com/JashirDev/t2-project.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}


